"""MorphableMesh: base mesh + modifiers -> morphed mesh.

`DifferentialTargetBuilder` derives targets the way most MakeHuman targets were
authored in practice: sculpt a variant of the base (here: re-run the parametric
generator with one parameter changed) and store the vertex difference.  Because
the generator has fixed topology, every derived target is compatible and can be
blended linearly with any other.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Callable, Dict, Iterable, List, Optional, Tuple
import numpy as np

from ..geometry.mesh import Mesh
from .target import Target, Modifier


class MorphableMesh:
    def __init__(self, base: Mesh, name: str = "morphable"):
        self.base = base
        self.name = name
        self.modifiers: Dict[str, Modifier] = {}
        self.targets: Dict[str, Target] = {}

    # ------------------------------------------------------------ registry
    def add_target(self, target: Target) -> Target:
        if target.n_vertices != self.base.n_vertices:
            raise ValueError(f"target {target.name} has {target.n_vertices} rows, base has {self.base.n_vertices}")
        self.targets[target.name] = target
        return target

    def add_modifier(self, mod: Modifier) -> Modifier:
        for t in (mod.incr, mod.decr):
            if t is not None and t.name not in self.targets:
                self.add_target(t)
        self.modifiers[mod.name] = mod
        return mod

    def modifier_names(self, group: Optional[str] = None) -> List[str]:
        return [m.name for m in self.modifiers.values() if group is None or m.group == group]

    # ------------------------------------------------------------- morphing
    def displacement(self, values: Dict[str, float]) -> np.ndarray:
        disp = np.zeros_like(self.base.vertices)
        for name, value in values.items():
            if value is None or abs(value) < 1e-12:
                continue
            mod = self.modifiers.get(name)
            if mod is None:
                raise KeyError(f"unknown modifier {name!r}; available: {sorted(self.modifiers)}")
            for target, w in mod.weights(float(value)):
                disp += target.offsets * w
        return disp

    def morph(self, values: Optional[Dict[str, float]] = None, extra_offsets: Optional[np.ndarray] = None) -> Mesh:
        mesh = self.base.copy()
        disp = self.displacement(values or {})
        if extra_offsets is not None:
            disp = disp + extra_offsets
        mesh.vertices = mesh.vertices + disp
        # decorative lines are regenerated by callers; drop stale ones
        mesh.lines, mesh.line_names = [], []
        return mesh

    def describe(self) -> List[dict]:
        return [m.to_dict() for m in self.modifiers.values()]


@dataclass
class ModifierSpec:
    """How to derive a modifier from a generator parameter."""

    param: str
    delta_minus: float
    delta_plus: float
    group: str = "shape"
    description: str = ""
    name: Optional[str] = None
    lower_bound: Optional[float] = None
    upper_bound: Optional[float] = None


class DifferentialTargetBuilder:
    """Builds a MorphableMesh from a parametric, fixed-topology generator.

    generator(params) -> Mesh must return the same topology for any params in
    range.  `params` is a dataclass-like object with attribute access; we copy it
    with `dataclasses.replace`.
    """

    def __init__(self, generator: Callable[[Any], Mesh], canonical_params: Any, name="morphable"):
        self.generator = generator
        self.canonical = canonical_params
        self.name = name
        self._cache: Dict[Tuple, np.ndarray] = {}

    def _build(self, **overrides) -> Mesh:
        import dataclasses

        p = dataclasses.replace(self.canonical, **overrides)
        return self.generator(p)

    def build(self, specs: Iterable[ModifierSpec], macros: Optional[Dict[str, Any]] = None,
              macro_group: str = "style") -> MorphableMesh:
        base = self._build()
        mm = MorphableMesh(base, self.name)
        for spec in specs:
            value = getattr(self.canonical, spec.param)
            name = spec.name or spec.param
            incr = decr = None
            if spec.delta_plus:
                hi = value + spec.delta_plus
                if spec.upper_bound is not None:
                    hi = min(hi, spec.upper_bound)
                v = self._build(**{spec.param: hi})
                incr = Target.from_difference(f"{name}-incr", base.vertices, v.vertices, f"{spec.param} {value:g} -> {hi:g}")
            if spec.delta_minus:
                lo = value - spec.delta_minus
                if spec.lower_bound is not None:
                    lo = max(lo, spec.lower_bound)
                v = self._build(**{spec.param: lo})
                decr = Target.from_difference(f"{name}-decr", base.vertices, v.vertices, f"{spec.param} {value:g} -> {lo:g}")
            mm.add_modifier(
                Modifier(name, incr, decr, -1.0 if decr is not None else 0.0, 1.0, 0.0, spec.group,
                         spec.description or f"{spec.param} (canonical {value:g})", unit_scale=spec.delta_plus)
            )
        for mname, mparams in (macros or {}).items():
            v = self.generator(mparams)
            t = Target.from_difference(f"{macro_group}-{mname}", base.vertices, v.vertices, f"macro {mname}")
            mm.add_modifier(Modifier(f"{macro_group}/{mname}", t, None, 0.0, 1.0, 0.0, macro_group, f"macro target: {mname}"))
        return mm
